<style>
/* notebook-style-v1: dark-theme-first markdown presentation */

.jp-MarkdownCell .jp-RenderedHTMLCommon,
.text_cell_render,
.markdown-body {
  color: #d7e0e7;
  line-height: 1.8;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon h1,
.text_cell_render h1,
.markdown-body h1 {
  background: linear-gradient(135deg, #22313d 0%, #284740 100%);
  color: #edf5f3;
  padding: 18px 22px;
  border-radius: 20px;
  border: 1px solid #3a5255;
  border-left: 10px solid #78b0a1;
  box-shadow: 0 10px 24px rgba(0, 0, 0, 0.20);
  margin: 0 0 18px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon h2,
.text_cell_render h2,
.markdown-body h2 {
  background: linear-gradient(90deg, #22313d 0%, #273743 100%);
  border-left: 8px solid #72aa9b;
  color: #e7eff3;
  padding: 11px 16px;
  border-radius: 14px;
  border: 1px solid #3a4b58;
  box-shadow: 0 6px 18px rgba(0, 0, 0, 0.18);
  margin: 22px 0 14px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon h3,
.text_cell_render h3,
.markdown-body h3 {
  display: inline-block;
  color: #d8e4ea;
  background: #22303a;
  border-left: 5px solid #7fa89e;
  padding: 8px 14px;
  border-radius: 12px;
  border: 1px solid #3a4a52;
  margin: 18px 0 10px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon h4,
.text_cell_render h4,
.markdown-body h4 {
  color: #9fd2c3;
  margin: 16px 0 8px 0;
  font-weight: 700;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon p,
.jp-MarkdownCell .jp-RenderedHTMLCommon li,
.text_cell_render p,
.text_cell_render li,
.markdown-body p,
.markdown-body li {
  color: #d7e0e7;
  line-height: 1.8;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon ul,
.jp-MarkdownCell .jp-RenderedHTMLCommon ol,
.text_cell_render ul,
.text_cell_render ol,
.markdown-body ul,
.markdown-body ol {
  margin: 10px 0 16px 20px;
  padding-left: 18px;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon li,
.text_cell_render li,
.markdown-body li {
  margin: 6px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon blockquote,
.text_cell_render blockquote,
.markdown-body blockquote {
  margin: 14px 0;
  padding: 12px 16px;
  background: #24313d;
  border-left: 5px solid #90b7a2;
  border-radius: 14px;
  border: 1px solid #3c4d5a;
  color: #d9e4ec;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon blockquote p,
.text_cell_render blockquote p,
.markdown-body blockquote p {
  margin: 6px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon pre,
.text_cell_render pre,
.markdown-body pre {
  background: #1b2330;
  color: #e6edf3;
  padding: 14px 16px;
  border-radius: 14px;
  border: 1px solid #334155;
  overflow-x: auto;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon code,
.text_cell_render code,
.markdown-body code {
  background: #27313a;
  color: #e8eef4;
  padding: 2px 6px;
  border-radius: 6px;
  border: 1px solid #3c4a55;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon pre code,
.text_cell_render pre code,
.markdown-body pre code {
  background: transparent;
  border: 0;
  padding: 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon hr,
.text_cell_render hr,
.markdown-body hr {
  border: 0;
  height: 1px;
  background: linear-gradient(90deg, transparent, #556977, transparent);
  margin: 20px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon table,
.text_cell_render table,
.markdown-body table {
  border-collapse: collapse;
  background: #ffffff;
  color: #31475b;
  font-size: 0.96rem;
  margin: 16px 0;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon thead th,
.text_cell_render thead th,
.markdown-body thead th {
  background: #f3f6f8;
  color: #24415c;
  padding: 10px 12px;
  text-align: left;
  border: 1px solid #dde6ec;
  font-weight: 700;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon tbody td,
.text_cell_render tbody td,
.markdown-body tbody td {
  padding: 10px 12px;
  border: 1px solid #e4edf2;
  vertical-align: top;
  color: #31475b;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon tbody tr:nth-child(even) td,
.text_cell_render tbody tr:nth-child(even) td,
.markdown-body tbody tr:nth-child(even) td {
  background: #f8fbff;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon a,
.text_cell_render a,
.markdown-body a {
  color: #8fd1ff;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon summary,
.text_cell_render summary,
.markdown-body summary {
  color: #e6edf3;
  cursor: pointer;
  font-weight: 700;
}

.jp-MarkdownCell .jp-RenderedHTMLCommon mjx-container,
.text_cell_render mjx-container,
.markdown-body mjx-container {
  color: #e6edf3 !important;
}
</style>
<div data-notebook-style-version="2026-04-v1" style="display:none;"></div>


#Introduction to PyTorch (Part 1)

## A.1 What is PyTorch

![figure](https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781633437166/files/OEBPS/Images/A-1.png)

**A.  Tensors: The Foundation**

As described in the provided text, tensors are the fundamental data structure in PyTorch.  They are multi-dimensional arrays, similar to NumPy's `ndarray`, but with crucial additions for deep learning:

*   **GPU Support:**  PyTorch tensors can reside on GPUs, enabling significant acceleration of computations. This is *essential* for training large models like LLMs.
*   **Automatic Differentiation:** PyTorch tracks operations performed on tensors, allowing for automatic gradient computation (more on this later).

In [1]:
import torch

print(torch.__version__)

2.2.0+cpu


In [2]:
print(torch.cuda.is_available())

False


## A.2 Understanding tensors

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/6.webp" width="400px">

### A.2.1 Scalars, vectors, matrices, and tensors

In [3]:
import torch
import numpy as np

# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], 
                         [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], 
                           [[5, 6], [7, 8]]])

# create a 3D tensor from NumPy array
ary3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d)  # Copies NumPy array
tensor3d_3 = torch.from_numpy(ary3d)  # Shares memory with NumPy array

In [4]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # remains unchanged

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [5]:
print(tensor3d_3) # changes because of memory sharing

tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


### A.2.2 Tensor data types

**A.1.  Tensor Creation and Manipulation (Expanded)**

Beyond `torch.tensor()`, here are essential tensor creation and manipulation functions you'll use constantly:

*   `torch.zeros(shape)`: Creates a tensor filled with zeros.  Useful for initializing bias terms or padding.



In [3]:
import torch
bias = torch.zeros(10)  # A 1D tensor of size 10, filled with 0s
print(bias)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



*   `torch.ones(shape)`: Creates a tensor filled with ones.
 


In [4]:
ones_tensor = torch.ones(2, 3)  # A 2x3 tensor filled with 1s
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])



*   `torch.randn(shape)`: Creates a tensor filled with random numbers drawn from a standard normal distribution (mean 0, variance 1).  Crucial for initializing weights.


In [ ]:
weights = torch.randn(5, 10)  # A 5x10 tensor with random values
print(weights)

tensor([[-0.8436,  1.6805,  0.6947, -0.5736, -1.1384,  1.6354,  0.3962,  0.1633,
          0.7605,  1.5464],
        [-0.4652,  1.8648,  0.2291, -1.1570,  1.3042,  0.9551,  0.3471, -1.1867,
          1.3027, -0.4717],
        [ 0.5114,  0.7470, -2.0746, -1.1638,  0.9471, -0.6478, -0.3342,  0.4323,
          0.9220,  0.8678],
        [ 0.4451,  1.7392, -0.1190, -0.6187,  0.2152,  0.4869, -0.6564,  0.6208,
         -0.5530,  0.4437],
        [ 0.9319,  0.6600, -0.1138,  0.7801,  0.3635, -0.7451,  0.5246, -1.2762,
          0.6958, -1.1870]])



*   `torch.arange(start, end, step)`: Creates a 1D tensor with values ranging from `start` to `end` (exclusive), with a specified `step`.



In [6]:
    sequence = torch.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
    print(sequence)

tensor([0, 2, 4, 6, 8])



*   `torch.linspace(start, end, steps)`: Creates a 1D tensor with `steps` evenly spaced values between `start` and `end` (inclusive).



In [7]:
    linspace_tensor = torch.linspace(0, 1, 5)  # [0.  , 0.25, 0.5 , 0.75, 1.  ]
    print(linspace_tensor)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])



*   `tensor.to(device)`:  Moves a tensor to a specific device (CPU or GPU).
    ```python
    if torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

    weights = weights.to(device)  # Move the weights to the GPU if available
    ```

In [6]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [7]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [8]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


### A.2.3 Common PyTorch tensor operations

In [9]:
tensor2d = torch.tensor([[1, 2, 3], 
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
tensor2d.shape

torch.Size([2, 3])

In [11]:
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

*   `tensor.view(shape)` / `tensor.reshape(shape)`:  Reshapes a tensor.  As mentioned, `view` requires contiguous memory, while `reshape` is more flexible.  You'll use this *very* frequently to change the dimensions of tensors to match the requirements of different layers.

In [8]:
batch = torch.randn(64,10,20)
batch

tensor([[[ 1.3011e+00,  5.7138e-01, -2.0467e-01,  ...,  7.5260e-01,
          -1.3397e+00,  1.9142e-01],
         [-1.9776e-01, -8.3684e-01, -2.5711e-01,  ...,  2.2043e+00,
          -2.5936e+00,  5.9766e-01],
         [ 4.8671e-01,  3.1572e-01, -1.6888e+00,  ..., -4.6810e-01,
          -2.5921e+00, -9.0415e-01],
         ...,
         [ 1.5478e+00, -1.3768e+00,  3.7523e-01,  ..., -9.9768e-01,
          -7.1774e-01, -2.2978e-01],
         [-1.1814e+00, -1.2629e+00, -1.7434e-01,  ...,  1.8147e-01,
          -8.9132e-01,  1.3017e+00],
         [ 9.4728e-01, -6.8306e-01,  1.1413e+00,  ...,  5.9322e-01,
           1.5622e-01,  4.4133e-02]],

        [[ 9.0515e-01,  3.3804e-01,  7.2782e-01,  ...,  5.6767e-02,
           8.2660e-01,  9.1113e-01],
         [ 9.1881e-01,  7.0406e-02,  1.4129e-01,  ..., -1.8948e+00,
          -8.3988e-01, -1.0722e-01],
         [ 7.1147e-01, -7.2496e-01, -4.7877e-01,  ...,  5.2587e-02,
          -1.1832e+00, -2.4583e-02],
         ...,
         [-1.4716e+00, -1

In [9]:
flattensor = batch.view(64,-1)
flattensor.shape, flattensor

(torch.Size([64, 200]),
 tensor([[ 1.3011,  0.5714, -0.2047,  ...,  0.5932,  0.1562,  0.0441],
         [ 0.9052,  0.3380,  0.7278,  ...,  0.2926,  0.7275, -1.0766],
         [-1.6943, -0.0469,  0.3629,  ...,  3.2171, -0.3963,  0.8402],
         ...,
         [-0.0826,  0.0989, -0.4069,  ..., -1.0591, -0.8052, -0.8795],
         [ 0.2215, -0.7329,  0.5300,  ...,  0.9335, -1.1796, -0.2935],
         [ 0.8524,  1.1920, -0.4700,  ..., -0.3607, -0.5179,  1.8232]]))

*   `tensor.transpose(dim0, dim1)` / `tensor.permute(dims)`: Transposes or permutes the dimensions of a tensor.  `transpose` swaps two dimensions, while `permute` allows for more general reordering.

In [12]:
matrix = torch.randn(3, 5)
transposed = matrix.transpose(0, 1)  # Swap rows and columns
print(transposed.shape)

tensor3d = torch.randn(2, 3, 4)
permuted = tensor3d.permute(2, 0, 1)  # Reorder dimensions
print(permuted.shape) #torch.Size([4, 2, 3])
tensor3d,permuted

torch.Size([5, 3])
torch.Size([4, 2, 3])


(tensor([[[ 0.2035, -1.1944, -0.4008, -3.8380],
          [ 0.6790, -0.1748,  1.6139, -0.6213],
          [ 0.0253, -0.7084,  1.0584, -0.9450]],
 
         [[-1.4716, -0.1927, -0.2412, -1.1469],
          [-0.7180,  0.8126,  0.9421, -1.2932],
          [ 1.5454, -0.5728, -0.0414, -0.4523]]]),
 tensor([[[ 0.2035,  0.6790,  0.0253],
          [-1.4716, -0.7180,  1.5454]],
 
         [[-1.1944, -0.1748, -0.7084],
          [-0.1927,  0.8126, -0.5728]],
 
         [[-0.4008,  1.6139,  1.0584],
          [-0.2412,  0.9421, -0.0414]],
 
         [[-3.8380, -0.6213, -0.9450],
          [-1.1469, -1.2932, -0.4523]]]))

In [14]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [15]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

### PyTorch `squeeze()` and `unsqueeze()` Operations Explained

These two operations are used to manipulate tensor dimensions, specifically adding or removing dimensions of size 1.

---

### **1. `torch.squeeze()`**
#### **Functionality**: Removes dimensions of size **1** from a tensor.
#### **Syntax**:
```python
torch.squeeze(input, dim=None)
```
- `input`: The input tensor.
- `dim` (optional): The specific dimension to squeeze. If not provided, all dimensions of size `1` are removed.

#### **Example 1: Removing all dimensions of size 1**
```python
import torch

x = torch.rand(1, 3, 1, 5)  # Shape: [1, 3, 1, 5]
y = torch.squeeze(x)        # Shape: [3, 5]

print(y.shape)  # Output: torch.Size([3, 5])
```

#### **Example 2: Removing a specific dimension**
```python
x = torch.rand(1, 3, 1, 5)   # Shape: [1, 3, 1, 5]
y = torch.squeeze(x, dim=0)  # Removes the first dimension
print(y.shape)  # Output: torch.Size([3, 1, 5])
```
> If the specified `dim` is **not** of size `1`, the tensor remains unchanged.

---

### **2. `torch.unsqueeze()`**
#### **Functionality**: Adds a new dimension of size **1** at the specified index.
#### **Syntax**:
```python
torch.unsqueeze(input, dim)
```
- `input`: The input tensor.
- `dim`: The dimension where a new axis (size 1) should be inserted.

#### **Example 1: Adding a new dimension**
```python
x = torch.rand(3, 5)       # Shape: [3, 5]
y = torch.unsqueeze(x, 0)  # Adds a new dimension at index 0

print(y.shape)  # Output: torch.Size([1, 3, 5])
```

#### **Example 2: Adding a new dimension at the end**
```python
y = torch.unsqueeze(x, -1)  # Adds a new dimension at the last index
print(y.shape)  # Output: torch.Size([3, 5, 1])
```

---

### **Use Cases**
- `squeeze()`: Useful for removing unnecessary singleton dimensions.
- `unsqueeze()`: Useful when reshaping tensors for operations like broadcasting or passing inputs to models expecting specific shapes.

Let me know if you need more clarification! 🚀

### Quick Review

In [ ]:
import torch

# Creating a tensor of shape (64, 3, 32, 32) - let's say it represents a batch of 64 images with 3 channels (RGB) and size 32x32.
batch = torch.randn(64, 3, 32, 32)

# Flattening the tensor to shape (64, -1), where -1 means infer the size based on other dimensions
flattensor = batch.view(64, -1)

# Printing the shape of the flattened tensor
print(f"Flattened tensor shape: {flattensor.shape}")  # Expected: torch.Size([64, 3072])

In [ ]:
import torch

# Create a tensor of shape (16, 3, 64, 64) representing a batch of 16 RGB images of size 64x64
batch = torch.randn(16, 3, 64, 64)

# Flatten the tensor to shape (16, -1)
flattened_batch = batch.view(16, -1)

# Print the shape of the flattened tensor
print(f"Flattened batch shape: {flattened_batch.shape}")  # Expected: torch.Size([16, 12288])


In [ ]:
import torch

# Create a tensor of size (2, 3, 4)
tensor = torch.randn(2, 3, 4)

# Use .view() to flatten this tensor into a 2D tensor
flattened_tensor = tensor.view(2, -1)

print(f"Flattened tensor: {flattened_tensor.shape}")  # Expected: torch.Size([2, 12])


In [ ]:
import torch

# Create a tensor of shape (64, 2, 2)
tensor = torch.randn(64, 2, 2)

# Reshaping the tensor into (64, -1) (flattening the last 2 dimensions)
reshaped_tensor = tensor.view(64, -1)

# Print the shape of the reshaped tensor
print(f"Reshaped tensor: {reshaped_tensor.shape}")  # Expected: torch.Size([64, 4])


In [ ]:
import torch

# Create a 3D tensor of shape (128, 3, 256)
tensor_3d = torch.randn(128, 3, 256)

# Flatten the tensor into 2D with 128 rows and the product of 3 * 256 columns
flattened_tensor = tensor_3d.view(128, -1)

print(f"Flattened tensor: {flattened_tensor.shape}")  # Expected: torch.Size([128, 768])


In [ ]:
import torch

# Create a tensor of shape (4, 3, 6)
tensor = torch.randn(4, 3, 6)

# Use .view() with `-1` to flatten it along a specific dimension
flattened_tensor = tensor.view(4, -1)  # Automatically infer the correct size

print(f"Flattened tensor shape: {flattened_tensor.shape}")  # Expected: torch.Size([4, 18])


In [ ]:
import torch

# Create a tensor of shape (2, 3, 4)
tensor = torch.randn(2, 3, 4)

# Transpose the tensor, changing its layout
transposed_tensor = tensor.transpose(1, 2)  # Swap the 2nd and 3rd dimensions

# Make the tensor contiguous (needed after transposition for reshaping)
contiguous_tensor = transposed_tensor.contiguous()

# Now reshape it
reshaped_tensor = contiguous_tensor.view(2, -1)

print(f"Reshaped tensor after transposition: {reshaped_tensor.shape}")  # Expected: torch.Size([2, 12])


In [ ]:
import torch
import torch.nn as nn

# Create a sample input tensor of shape (1, 256, 8, 8) simulating a batch of images
input_tensor = torch.randn(1, 256, 8, 8)

# Define a simple linear layer after flattening the input
class FlattenAndLinear(nn.Module):
    def __init__(self):
        super(FlattenAndLinear, self).__init__()
        self.flatten = nn.Flatten()  # Flatten the input tensor
        self.fc = nn.Linear(256*8*8, 10)  # Fully connected layer (10 output classes)

    def forward(self, x):
        x = self.flatten(x)  # Flatten the input
        x = self.fc(x)  # Pass through a fully connected layer
        return x

# Instantiate the model
model = FlattenAndLinear()

# Pass the input tensor through the model
output = model(input_tensor)

print(f"Output shape: {output.shape}")  # Expected: torch.Size([1, 10])


Okay, let's significantly expand that table to include more crucial operations commonly used in LLM and deep learning contexts, along with specific examples related to those fields. I'll categorize them for clarity and add more "Points to Remember" that are particularly relevant for interviews.

**Expanded PyTorch Tensor Operations for LLMs and Deep Learning**

| **Category** | **Operation** | **Description** | **When to Use (LLM/DL Specific)** | **Points to Remember (Interview Focus)** | **Example** |
|---|---|---|---|---|---|
| **Reshaping & Dimensionality** | `view()`      | Reshape a tensor (contiguous). |  - Changing the shape of embeddings before feeding into a Transformer layer.  - Reshaping the output of a convolutional layer before a fully connected layer. | - Requires the tensor to be contiguous. Use `.contiguous()` if needed.  - Total number of elements must remain the same. -1 can be used for one dimension to infer the size. | `embeddings = embeddings.view(batch_size, seq_len, -1)` |
|  | `reshape()`   | Reshape a tensor (handles non-contiguous). | - Same use cases as `view()`, but when you're unsure if the tensor is contiguous (e.g., after transposing).  | - More flexible than `view()` as it handles non-contiguous tensors. Will copy data if necessary. | `output = output.reshape(batch_size, -1)` |
|  | `squeeze()`   | Remove dimensions of size 1. | - Removing singleton dimensions from model outputs (e.g., removing a batch dimension of 1 after processing a single example).  - Getting rid of unnecessary dimensions after certain operations. | - Useful for cleaning up tensor shapes. Be mindful of which dimension you're squeezing. | `prediction = prediction.squeeze(0)` (remove batch dimension) |
|  | `unsqueeze()` | Add a dimension of size 1. | - Adding a batch dimension to a single input sequence.  - Adding a channel dimension to grayscale images.  - Preparing data for layers that expect a certain number of dimensions. | - Often used to prepare data for batch processing.  Specify the dimension where you want to add the singleton dimension. | `input_sequence = input_sequence.unsqueeze(0)` (add batch dimension) |
|  | `transpose()` | Swap two dimensions. | - Swapping the sequence length and embedding dimensions in recurrent networks.  - Converting between channel-first and channel-last image formats. | - Limited to swapping *two* dimensions.  Commonly used to prepare data for different layer types. | `hidden_states = hidden_states.transpose(0, 1)` (swap sequence and batch) |
|  | `permute()`   | Reorder dimensions arbitrarily. | - Changing the order of dimensions to match the expected input format of a layer (e.g., for attention mechanisms). | - More general than `transpose()`; allows reordering of any number of dimensions.  Specify the new order of dimensions as a tuple. | `attention_input = attention_input.permute(2, 0, 1)` |
|  | `flatten()`   | Flatten a tensor into a 1D vector. | - Converting the output of convolutional layers or recurrent layers into a vector before feeding it into a fully connected layer. | - Creates a contiguous 1D view.  Often used before `nn.Linear` layers. | `features = features.flatten(start_dim=1)` |
| **Combining Tensors** | `cat()`       | Concatenate tensors along an existing dimension. | - Combining the outputs of multiple recurrent layers.  - Concatenating embeddings from different sources.  - Building batches of data. | - Tensors must have the same shape *except* for the dimension along which you're concatenating.  Specify the `dim` argument. | `combined_embeddings = torch.cat([embed1, embed2], dim=1)` |
|  | `stack()`     | Stack tensors along a *new* dimension. | - Creating a batch of sequences where each sequence was previously a separate tensor.  - Combining multiple feature maps. | - All tensors must have the *same* shape.  Specify the `dim` argument to indicate where the new dimension should be added. | `batch = torch.stack([seq1, seq2, seq3], dim=0)` |
| **Memory Management** | `contiguous()` | Ensure a tensor is contiguous in memory. | - Before using `view()`. - After operations like `transpose()` or `permute()` that might make a tensor non-contiguous. - Some operations require contiguous tensors; this ensures compatibility.  | - If you get an error about a tensor not being contiguous, call this before reshaping.  | `tensor = tensor.transpose(0, 1).contiguous()` |
|  | `clone()`     | Create a deep copy of a tensor. | - When you need to modify a tensor without affecting the original.  - Creating copies of model parameters for certain optimization techniques. | - Creates a completely independent copy, including the data and gradient information (if applicable). | `copied_weights = model.weights.clone()` |
|  | `detach()`    | Create a tensor detached from the computation graph. | - Preventing gradients from flowing back through a certain part of the computation. - When you want to use a tensor's values for calculations but don't need gradients. - When you want to move the tensor to another framework and don't need the computational graph. | - The detached tensor shares the same data as the original but doesn't track operations for autograd.  Essential for preventing unintended gradient updates. | `hidden_state = hidden_state.detach()` (prevent backpropagation through time) |
| **Element-wise Operations** | `+`, `-`, `*`, `/` | Element-wise addition, subtraction, multiplication, division. | - Standard arithmetic operations on tensors. - Implementing custom activation functions or loss functions. | - Operations are performed element-by-element. Tensors must have compatible shapes (broadcasting rules apply, like NumPy). | `result = tensor1 * tensor2 + tensor3` |
|  | `torch.add()`, `torch.sub()`, `torch.mul()`, `torch.div()` | Explicit element-wise operations. | Same as +, -, *, /, but can handle non-contigious tensor. | `out = torch.add(input, other, out=out)` |
| | `pow()` | Apply element wise power.| Applying exponential function.| Tensors must have compatible shapes (broadcasting rules apply, like NumPy). | `result = tensor1.pow(2)` |
| | `exp()` | Apply element wise exp.| Applying exponential function.| Tensors must have compatible shapes (broadcasting rules apply, like NumPy). | `result = tensor1.exp()` |
| | `log()` | Apply element wise log.| Applying log function.| Tensors must have compatible shapes (broadcasting rules apply, like NumPy). | `result = tensor1.log()` |
| **Matrix Operations** | `matmul()` / `@` | Matrix multiplication. | - Implementing linear layers. - Performing attention calculations. | - The inner dimensions must match (e.g., (m x n) @ (n x p) -> (m x p)).  `@` is a shorthand for `matmul()`. | `output = torch.matmul(input, weights) + bias`  or  `output = input @ weights + bias` |
|  | `bmm()`       | Batch matrix multiplication. | - Performing matrix multiplications on batches of matrices. - Common in recurrent networks and attention mechanisms. | - Input tensors must have 3 dimensions (batch, n, m) and (batch, m, p). | `output = torch.bmm(batch_of_matrices1, batch_of_matrices2)` |
|  | `einsum()`    | Einstein summation. | - Performing complex tensor contractions and summations, including matrix multiplication, dot products, and more.  - Very powerful for implementing attention mechanisms. | - Requires understanding the Einstein summation notation. Can be significantly more efficient than combinations of other operations for certain computations. | `attention_weights = torch.einsum('bhid,bhjd->bhij', query, key)` (simplified attention) |
| **Reduction Operations** | `sum()`       | Sum of all elements or along a dimension. | - Calculating the total loss over a batch.  - Computing norms. | - Specify the `dim` argument to sum along a specific dimension.  `keepdim=True` can be used to keep the reduced dimension with size 1. | `total_loss = loss.sum()` or `row_sums = tensor.sum(dim=1)` |
|  | `mean()`      | Mean of all elements or along a dimension. | - Calculating the average loss over a batch. | - Similar to `sum()`, but computes the average. | `average_loss = loss.mean()` |
|  | `max()` / `min()` | Maximum/minimum value (and optionally indices). | - Finding the maximum activation in a layer.  - Getting the predicted class in classification (using `argmax`). | - `max()` and `min()` return a tuple: (values, indices).  `argmax()` returns only the indices. | `max_value, max_index = tensor.max(dim=1)` |
|  | `argmax()` / `argmin()` | Index of the maximum/minimum value. | - Getting the predicted class label in classification. | - Returns the *index* of the maximum/minimum value. Specify the `dim` argument. | `predicted_class = output.argmax(dim=1)` |
|  |`topk()` |Returns the k largest elements of the given input tensor along a given dimension| When you are only intrested with the top k items| `values, indices = x.topk(k)`|
| **Indexing and Slicing** | `[]`          | Indexing and slicing tensors. | - Accessing specific elements or sub-tensors.  - Selecting data based on conditions. | - Similar to NumPy indexing.  Use integers, slices, and boolean masks. | `element = tensor[2, 3]` , `sub_tensor = tensor[:, 1:4]` , `selected = tensor[tensor > 0]` |
|  | `gather()`    | Gather values along an axis specified by indices. | - Selecting specific embeddings based on token IDs.  - Implementing attention mechanisms where you need to select specific hidden states. | - The `dim` argument specifies the axis along which to gather.  The `index` tensor specifies the indices to select. | `selected_embeddings = torch.gather(embeddings, 1, token_ids)` |
|  | `scatter_()` | Scatter values into a tensor at specified indices (in-place). | - Updating specific elements in a tensor based on indices. - Implementing custom operations that require modifying specific locations. | - The opposite of `gather()`.  The `dim` argument specifies the axis, and `index` specifies where to scatter the values from the `src` tensor. The underscore indicates in-place modification.| `tensor.scatter_(1, indices, values)` |
| **Comparison Operations** | `==`, `!=`, `<`, `>`, `<=`, `>=` | Element-wise comparison. | - Creating boolean masks for filtering tensors.  - Checking for equality or inequality. | - Returns a boolean tensor of the same shape. | `mask = tensor > 0` |
|  | `torch.eq()`, `torch.ne()`, `torch.lt()`, `torch.gt()`, `torch.le()`, `torch.ge()` |Explicit comparison | Use when you need to handle cases where tensors might not be contiguous. | `mask = torch.gt(tensor,0)` |
| **Boolean Operations** | `&`, `|`, `~`    | Element-wise logical AND, OR, NOT. | - Combining boolean masks. | - Operates on boolean tensors. | `combined_mask = mask1 & mask2` |
| **Other Useful Operations** | `clamp()`     | Clamp values within a range. | - Preventing exploding gradients by clipping values.  - Implementing certain activation functions. | - `input.clamp(min, max)` limits values to the range [min, max]. | `clipped_tensor = tensor.clamp(-1, 1)` |
|  | `isnan()` / `isinf()` | Check for NaN (Not a Number) or Inf (Infinity) values. | - Debugging numerical issues during training. | - Returns a boolean tensor. | `nan_mask = torch.isnan(tensor)` |
|  | `where()`    | Conditional selection based on a boolean mask. | Select values if true, and another value of false. | `result = torch.where(condition, x, y)`|




## A.3 Seeing models as computation graphs

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/7.webp" width="600px">

> PyTorch builds such a computation graph in the background, and we can use this to calculate gradients of a loss function with respect to the model parameters (here w1 and b) to train the model.

> If we carry out computations in PyTorch, it will build a computational graph internally by default if one of its terminal nodes has the requires_grad attribute set to True.

In [16]:
import torch.nn.functional as F

y = torch.tensor([1.0])  # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight parameter
b = torch.tensor([0.0])  # bias unit

z = x1 * w1 + b          # net input
a = torch.sigmoid(z)     # activation & output

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


## A.4 Automatic differentiation made easy

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/8.webp" width="600px">

##### Figure A.8 The most common way of computing the loss gradients in a computation graph involves applying the chain rule from right to left, also called reverse-model automatic differentiation or backpropagation. We start from the output layer (or the loss itself) and work backward through the network to the input layer. We do this to compute the gradient of the loss with respect to each parameter (weights and biases) in the network, which informs how we update these parameters during training.

In [17]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b 
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


> we can call .backward on the loss, and PyTorch will compute the gradients of all the leaf nodes in the graph, which will be stored via the tensors’ .grad attributes:

In [18]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## A.5 Implementing multilayer neural networks

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/9.webp" width="500px">

In [19]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
                
            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [20]:
model = NeuralNetwork(50, 3)

In [21]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [22]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


In [23]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.1182,  0.0606, -0.1292,  ..., -0.1126,  0.0735, -0.0597],
        [-0.0249,  0.0154, -0.0476,  ..., -0.1001, -0.1288,  0.1295],
        [ 0.0641,  0.0018, -0.0367,  ..., -0.0990, -0.0424, -0.0043],
        ...,
        [ 0.0618,  0.0867,  0.1361,  ..., -0.0254,  0.0399,  0.1006],
        [ 0.0842, -0.0512, -0.0960,  ..., -0.1091,  0.1242, -0.0428],
        [ 0.0518, -0.1390, -0.0923,  ..., -0.0954, -0.0668, -0.0037]],
       requires_grad=True)


In [24]:
torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [25]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [26]:
torch.manual_seed(123)

X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [27]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


> for example, if we use it for `prediction after training—constructing this computational graph for backpropagation can be wasteful as it performs unnecessary computations and consumes additional memory`. So, when we use a model for inference (for instance, making predictions) rather than training, `the best practice is to use the torch.no_grad() context manager`. `This tells PyTorch that it doesn’t need to keep track of the gradients, which can result in significant savings in memory and computation`:

In [28]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6 Setting up efficient data loaders

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/10.webp" width="600px">

In [29]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])

In [30]:
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [31]:
from torch.utils.data import Dataset


class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]        
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [32]:
len(train_ds)

5

In [33]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)

In [34]:
test_ds = ToyDataset(X_test, y_test)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [35]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [36]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [37]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/11.webp" width="600px">

> Figure A.11 Loading data without multiple workers (setting num_workers=0) will create a data loading bottleneck where the model sits idle until the next batch is loaded (left). If multiple workers are enabled, the data loader can queue up the next batch in the background (right).

## A.7 A typical training loop

In [38]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)
        
        loss = F.cross_entropy(logits, labels) # Loss function
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation

Epoch: 001/003 | Batch 000/002 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/002 | Train/Val Loss: 0.65
Epoch: 002/003 | Batch 000/002 | Train/Val Loss: 0.44
Epoch: 002/003 | Batch 001/002 | Train/Val Loss: 0.13
Epoch: 003/003 | Batch 000/002 | Train/Val Loss: 0.03
Epoch: 003/003 | Batch 001/002 | Train/Val Loss: 0.00


> To prevent undesired gradient accumulation, it is important to include an optimizer.zero_grad() call in each update round to reset the gradients to 0. Otherwise, the gradients will accumulate, which may be undesired.

In [39]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [40]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])
tensor([0, 0, 0, 1, 1])


In [41]:
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [42]:
predictions == y_train

tensor([True, True, True, True, True])

In [43]:
torch.sum(predictions == y_train)

tensor(5)

In [44]:
def compute_accuracy(model, dataloader):

    model = model.eval()
    correct = 0.0
    total_examples = 0
    
    for idx, (features, labels) in enumerate(dataloader):
        
        with torch.no_grad():
            logits = model(features)
        
        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()

In [45]:
compute_accuracy(model, train_loader)

1.0

In [46]:
compute_accuracy(model, test_loader)

1.0

## A.8 Saving and loading models

In [47]:
torch.save(model.state_dict(), "model.pth")

In [48]:
model = NeuralNetwork(2, 2) # needs to match the original model exactly
model.load_state_dict(torch.load("model.pth", weights_only=True))

<All keys matched successfully>

## A.9 Optimizing training performance with GPUs

### A.9.1 PyTorch computations on GPU devices

See [code-part2.ipynb](code-part2.ipynb)

### A.9.2 Single-GPU training

See [code-part2.ipynb](code-part2.ipynb)

### A.9.3 Training with multiple GPUs

See [DDP-script.py](DDP-script.py)